### ISSUE TITLE
Hardware spec used for handling 100k flows per seconds

### ISSUE THREAD

**Issue by nchauhan5** [cloudflare/flow-pipeline#19]
Reading the documentation (README), I can see that you have mentioned- 

"Using a production setup, GoFlow was able to process more than +100k flows per second and insert them in a Clickhouse database."

Can you please tell us the hardware specs of different components of the goflow pipeline you used for that?

**Comment by gaby** [comment]
👍🏻 for this

**Comment by taktv6** [comment]
I'm afraid our internal setup has changed since that statement was made.
Current benchmarks are not available from our side. Sorry.

**Comment by gaby** [comment]
@taktv6 Would it be possible to get a license added to this repo? Thanks!
