### ISSUE TITLE
inserter dies out in  collect configuration

### ISSUE THREAD

**Issue by egargale** [cloudflare/flow-pipeline#2]
Thank for GOFlow software. I am studying how to implement in my small network.

I started with flow-pipeline in a docker environment to better understand all the parts.

`docker-compose -f ./docker-compose-mock.yml up `

worked fine ! The problem is when I try

`docker-compose -f docker-compose-collect.yml up`

Apparently inserter dies at the kafka.broker creation. Error is the following:
  
`time="2019-08-09T14:52:02Z" level=fatal msg="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"`

the container restart (as per policy) and dies again. the export to postgresql do not occur.

What is surpring is that the **same inserter** container with the mock generation is working fine.
Maybe my knowledge on Kafka is still to limited to understand what is going on.
Regards
Enrico

Docker engine
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
```
Docker-compose version
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov OS 2018
```
OS system
`Fedora 30 workstation `

**Comment by scomoletti** [comment]
Edit docker-compose-collect.yml. 
Change line 41 from "-kafka.out.brokers' to "-kafka.brokers".
Change line 42 from "-kafka.out.topic" to "-kafka.topic"
Change line 72 and remove "/inserter " from the beginning of the line. 
Save, restart and it will work.

**Comment by lspgn** [comment]
Hello,
Thanks @scomoletti 
Sorry this has been open for way too long.
I just pushed a general update. It should be fixed now.
