### ISSUE TITLE
Bugs in docker-compose-collect.yml?

### ISSUE THREAD

**Issue by jysui123** [cloudflare/flow-pipeline#4]
Hi, 

I tried to run the pipeline specified by docker-compose-collect.yml, but it raises an error says that flag "kafka.broker.out" is not found. Is that a deprecated one?

Thank you so much!

**Comment by lspgn** [comment]
Similar to #2 
Flags have been updated for GoFlow (`kafka.brokers` instead of `kafka.brokers.out`)

Should be fixed now.
